### ISSUE TITLE
Why requiring node version >=16.8 ?

### ISSUE THREAD

**Issue by abenhamdine** [clerkinc/javascript#314]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Go through package changelog files. 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@clerk/remix@0.5.11',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v14.17.2', npm: '8.6.0' }
```

It is unusual to require such a higher version of nodejs.  
Not every user can migrate from nodejs14 to 16 because of many remaining incompatible modules.
Is that possible to loosen this requirement ?

**Comment by SokratisVidros** [comment]
HI @abenhamdine. [Remix](https://remix.run/docs/en/v1/tutorials/blog#prerequisites) sets the following requirements at the moment:

- [Node.js](https://nodejs.org/) version (^14.17.0, or >=16.0.0)

After [AWS switching to Node 16](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/) the main reason we opted for Node 16 was the availability of [webcrypto](https://nodejs.org/docs/latest-v16.x/api/webcrypto.html) in order to make our [SDKs isomorphic](https://github.com/clerkinc/javascript/issues/127) and lean without too many polyfills.

Which runtime are you using? Have you spotted the incompatible modules?
