### ISSUE TITLE
Expo Clerk provider crashes instantly

### ISSUE THREAD

**Issue by elmarvr** [clerkinc/javascript#621]
Clerk instantly crashes without error message.
ApiKey: clerk.trusty.dory-86.lcl.dev

**Comment by BrettCrowley77** [comment]
Same here. I couldn't get the starter example to work because of dependency conflicts in the package.json. I have the following installed in my environment:

- "@clerk/clerk-expo": "^0.10.15"
- "expo": "^47.0.8"
- "react": "18.1.0"
- "react-native": "0.70.5"

With the following App.js code, the app fails immediately without an error code, but with the warning 'Possible Unhandled Promise Rejection (id: 0).'

import React from 'react';
import {View, Text} from 'react-native';
import {ClerkProvider} from '@clerk/clerk-expo';

export default function App() {
  return (
    <ClerkProvider frontendApi={'clerk.guided.mule-18.lcl.dev'}>
      <View>
        <Text>Hello!</Text>
      </View>
    </ClerkProvider>
  );
}

**Comment by SokratisVidros** [comment]
Thanks for reporting. We will have a look a look and get back to you ASAP.

**Comment by SokratisVidros** [comment]
@BrettCrowley77 Your Frontend API key (https://clerk.guided.mule-18.lcl.dev) seems to point to a deleted Clerk instance. Can you please update it and try again?

**Comment by BrettCrowley77** [comment]
@SokratisVidros I deleted the original instance and created a different one (new API key: 'clerk.first.iguana-94.lcl.dev'), but it gives the same result.

**Comment by SokratisVidros** [comment]
As far as I can see, the 400 you got lacks the HTTP Authorization header. Please make sure that your [tokenCache](https://github.com/clerkinc/clerk-expo-starter/blob/main/App.tsx#L19) works as expected and sets the `""` value by default so that the header is present in the request.

**Comment by nikosdouvlis** [comment]
Hello everyone, the [clerk-expo-starter](https://github.com/clerkinc/clerk-expo-starter) has been updated to use the correct dependencies. The dependencies broke when React 18.2.0 released because that version wasn't explicitly listed as a peer dependency of `react-native`. Please pull the latest changes and run `npm i` again - you might need to delete `node_modules` first. Let me know if the build issue persist so I can help.

Regarding @BrettCrowley77 case, I couldn't reproduce the issue with the new frontendAPI. Could you please share more details about your test env? Are you using an emulator or a real device? What OS are you running on? Thanks!

**Comment by BrettCrowley77** [comment]
Thanks @SokratisVidros and @nikosdouvlis, I've got it working now.

**Comment by BrettCrowley77** [comment]
@nikosdouvlis this issue suddenly appeared again this morning for me. The following code throws 'Possible Unhandled Promise Rejection (id: 0)' as soon as the app loads. I'm running on windows using the Expo tunnel option, which until this morning was working with no issues. I was using the legacy frontendAPI key until this morning, I switched to the publishableKey to see if it would make a difference but same error.

`import React from "react";
import { Text, View } from "react-native";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { ClerkProvider } from "@clerk/clerk-expo";
import * as SecureStore from "expo-secure-store";

const tokenCache = {
  getToken(key) {
    return SecureStore.getItemAsync(key);
  },
  saveToken(key, val) {
    return SecureStore.setItemAsync(key, val);
  },
};

export default function App() {
  return (
    <ClerkProvider
      publishableKey={"pk_test_Y2xlcmsuZmlyc3QuaWd1YW5hLTk0LmxjbC5kZXYk"}
      tokenCache={tokenCache}
    >
      <SafeAreaProvider>
        <View>
          <Text>Hello world!</Text>
        </View>
      </SafeAreaProvider>
    </ClerkProvider>
  );
}`

**Comment by SokratisVidros** [comment]
Thanks for the update. We've managed to reproduce this and working on a fix.

**Comment by SokratisVidros** [comment]
@BrettCrowley77 can you please try again? The issue should be fixed now.

**Comment by BrettCrowley77** [comment]
@SokratisVidros it is working again, thanks!
