### ISSUE TITLE
Storing data without cookies

### ISSUE THREAD

**Issue by lukeshay** [clerkinc/javascript#83]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Go through package changelog files. 

# Description

I am experimenting with using Clerk with an Ionic mobile app. There is no dedicated package for this so I was attempting to use `@clerk/clerk-js` but it uses cookies to store data.

# Question

Is there a way to pass in a different way to store data?

**E.g.**

```js
import Clerk from "@clerk/clerk-js";

const store = {
  set: (key, value) => {
    // ...some set code
  },
  get: (key) => {
    // ...some get code
  },
};

const clerk = new Clerk('fronted-api', { store });
```

**Comment by SokratisVidros** [comment]
Hi @lukeshay. 

The Clerk long-lived `__client` JWT is stored in a cookie only in browsers. For native applications, the JWT can be transferred via the HTTP Authorization header. Our [Expo package](https://github.com/clerkinc/clerk-expo-starter/blob/main/cache.ts) demonstrates how to use the Frontend API and set the `_is_native=1` query parameter if necessary to instruct the API that it's a native application talking. 

As for storage, you can build a custom Ionic storage similar to the [Expo secure store](https://github.com/clerkinc/javascript/blob/main/packages/expo/src/cache.ts) and pass it to the <ClerkProvider/> via the `[tokenCache](https://github.com/clerkinc/javascript/blob/main/packages/expo/src/ClerkProvider.tsx#L14)` prop.

Let me know if this helps.

**Comment by lukeshay** [comment]
@SokratisVidros Thank you! I will give that a try and close this issue if it works.

**Comment by lukeshay** [comment]
This is shown on app startup even with a custom token cache

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-16 at 20 56 28](https://user-images.githubusercontent.com/38476395/158721353-110eafeb-ac1f-44e8-8b0f-c1bd4c2c3bd1.png)

**Comment by SokratisVidros** [comment]
@lukeshay Do you get that in the native application browser? Did you set the `?is_native=true` query string parameters to all the frontend API requests?

**Comment by lukeshay** [comment]
@SokratisVidros I was using `@clerk/clerk-expo`. Do I still need to add that flag when using that package? If so, how do I do that?

**Comment by SokratisVidros** [comment]
If you are using the package you shouldn't get that page. Do you maybe have a sample repo I can take a look at?

**Comment by lukeshay** [comment]
Here is a sample repo, <https://github.com/lukeshay/clerk-ionic>

**Comment by SokratisVidros** [comment]
I see. I am not very familiar with Ionic but to the best of my knowledge the runtime is a webview powered by Capacitor that triggers Clerk browser flow. 

In further detail, Clerk uses third party cookies for development instances in order to achieve seamless auth developer experience and avoid too much configuration in order to get started. To allow third party cookies in Safari the [Storage access api](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) is required. The modal asks for the user confirmation to enable the Storage access API. 

This modal should appear only once in development until the `Set up access` button is clicked and will never appear in production instances. 

Did you try to click on `Set up access`?

**Comment by SokratisVidros** [comment]
Hey @lukeshay. Any updates on this ☝️ ?

**Comment by lukeshay** [comment]
I have not bee able to test this but I assume you are correct here

**Comment by SokratisVidros** [comment]
👍 Let me know if you need further assistance.
